<a href="https://colab.research.google.com/github/chandanapalthiya14/2048/blob/main/00_tensorflow_fundementals.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
#in this notebook,we are going to cover some of the most fundemental concepts of tensors using tensorflow
#more specifically,we are going to cover:
#*introduction to tensors
#*getting info from tensors
#*manipulating tensors
#*tensors&numpy
#*using @tf.function(a way to speed up yyuor regular python functions)
#*using GPUs with tensorflow (or TPUs)
#*exercises to try yourself


In [ ]:
##introduction to tensors

In [1]:
# Import TensorFlow
import tensorflow as tf
print(tf.__version__)

2.17.1


In [2]:
# create tensors with tf.constant()
scalar=tf.constant(7)
scalar

<tf.Tensor: shape=(), dtype=int32, numpy=7>

In [3]:
# check the number of dimensions of a tensor (ndim stands for number of dimensions)
scalar.ndim

0

In [4]:
#create a vector
vector=tf.constant([10,10])
vector

<tf.Tensor: shape=(2,), dtype=int32, numpy=array([10, 10], dtype=int32)>

In [5]:
# check the dimensions of ur vector
vector.ndim

1

In [6]:
# create a matrix (has more than 1 dimension)
matrix=tf.constant([[10,7],
                   [7,10]])
matrix


<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[10,  7],
       [ 7, 10]], dtype=int32)>

In [7]:
matrix.ndim

2

In [10]:
# create another matrix
another_matrix=tf.constant([[10.,7.],
                            [3.,2.],
                            [8.,9,]],dtype=tf.float16)#specify the data type with dtype paramet
another_matrix


<tf.Tensor: shape=(3, 2), dtype=float16, numpy=
array([[10.,  7.],
       [ 3.,  2.],
       [ 8.,  9.]], dtype=float16)>

In [11]:
# what is the number dimensions of another_matrix
another_matrix.ndim

2

In [17]:
# lets create a tensor
tensor=tf.constant([[[1,2,3],
                    [4,5,6]],
                    [[7,8,9],
                    [10,11,12]],
                    [[13,14,15],
                     [16,17,18]]])
tensor

<tf.Tensor: shape=(3, 2, 3), dtype=int32, numpy=
array([[[ 1,  2,  3],
        [ 4,  5,  6]],

       [[ 7,  8,  9],
        [10, 11, 12]],

       [[13, 14, 15],
        [16, 17, 18]]], dtype=int32)>

*italicized text*

In [18]:
chandu=tf.constant(1,2)
chandu

<tf.Tensor: shape=(), dtype=float64, numpy=1.0>

In [19]:
tensor.ndim

3

#what we've created so far:
#*scalar:a single numbers
#*vector:a number with direction(eg:wind speed and direction)
#*matrix:a 2-dimensional array of numbers
#*tensor:a n-dimensional array of numbers(when n can be any number,a 0-dimensional tensor is a sclar,a 1-dimensional tensor is a vector)

In [20]:
tf.variable

AttributeError: module 'tensorflow' has no attribute 'variable'

In [21]:
tf.Variable

tensorflow.python.ops.variables.Variable

In [22]:
# create the same tensor with tf.Variable() as above
changeable_tensor=tf.Variable([10,7])
unchangeable_tensor=tf.constant([10,7])
changeable_tensor,unchangeable_tensor

(<tf.Variable 'Variable:0' shape=(2,) dtype=int32, numpy=array([10,  7], dtype=int32)>,
 <tf.Tensor: shape=(2,), dtype=int32, numpy=array([10,  7], dtype=int32)>)

In [23]:
#lets try change one of the elements in our chanegable tensor
changeable_tensor[0]=7
changeable_tensor

TypeError: 'ResourceVariable' object does not support item assignment

In [24]:
# lets try change our unchangeble tensor
unchangeable_tensor[0].assign(7)
unchangeable_tensor

AttributeError: 'tensorflow.python.framework.ops.EagerTensor' object has no attribute 'assign'

In [25]:
# how about we try .assign()
changeable_tensor[0].assign(7)
changeable_tensor

<tf.Variable 'Variable:0' shape=(2,) dtype=int32, numpy=array([7, 7], dtype=int32)>

In [26]:
#lets try change our unchangable tensor
unchangeable_tensor[0].assign(7)
unchangeable_tensor

AttributeError: 'tensorflow.python.framework.ops.EagerTensor' object has no attribute 'assign'

###creating random tensors
random tensors are tensors of some arbitary size which contain random numbers

In [ ]:
# create two random (but two same)tensors
random_1=tf.random.Generator.from_seed(42) #set seed for reproducibility
random_1=random_1.normal(shape=(3,2))
random_2=tf.random.Generator.from_seed(42)
random_2=random