<a href="https://colab.research.google.com/github/chandanapalthiya14/2048/blob/main/00_tensorflow_fundementals.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
#in this notebook,we are going to cover some of the most fundemental concepts of tensors using tensorflow
#more specifically,we are going to cover:
#*introduction to tensors
#*getting info from tensors
#*manipulating tensors
#*tensors&numpy
#*using @tf.function(a way to speed up yyuor regular python functions)
#*using GPUs with tensorflow (or TPUs)
#*exercises to try yourself


In [ ]:
##introduction to tensors

In [ ]:
# Import TensorFlow
import tensorflow as tf
print(tf.__version__)

2.17.1


In [ ]:
# create tensors with tf.constant()
scalar=tf.constant(7)
scalar

<tf.Tensor: shape=(), dtype=int32, numpy=7>

In [ ]:
# check the number of dimensions of a tensor (ndim stands for number of dimensions)
scalar.ndim

0

In [ ]:
#create a vector
vector=tf.constant([10,10])
vector

<tf.Tensor: shape=(2,), dtype=int32, numpy=array([10, 10], dtype=int32)>

In [ ]:
# check the dimensions of ur vector
vector.ndim

1

In [ ]:
# create a matrix (has more than 1 dimension)
matrix=tf.constant([[10,7],
                   [7,10]])
matrix


<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[10,  7],
       [ 7, 10]], dtype=int32)>

In [ ]:
matrix.ndim

2

In [ ]:
# create another matrix
another_matrix=tf.constant([[10.,7.],
                            [3.,2.],
                            [8.,9,]],dtype=tf.float16)#specify the data type with dtype paramet
another_matrix


<tf.Tensor: shape=(3, 2), dtype=float16, numpy=
array([[10.,  7.],
       [ 3.,  2.],
       [ 8.,  9.]], dtype=float16)>

In [ ]:
# what is the number dimensions of another_matrix
another_matrix.ndim

2

In [ ]:
# lets create a tensor
tensor=tf.constant([[[1,2,3],
                    [4,5,6]],
                    [[7,8,9],
                    [10,11,12]],
                    [[13,14,15],
                     [16,17,18]]])
tensor

<tf.Tensor: shape=(3, 2, 3), dtype=int32, numpy=
array([[[ 1,  2,  3],
        [ 4,  5,  6]],

       [[ 7,  8,  9],
        [10, 11, 12]],

       [[13, 14, 15],
        [16, 17, 18]]], dtype=int32)>

*italicized text*

In [ ]:
chandu=tf.constant(1,2)
chandu

<tf.Tensor: shape=(), dtype=float64, numpy=1.0>

In [ ]:
tensor.ndim

3

#what we've created so far:
#*scalar:a single numbers
#*vector:a number with direction(eg:wind speed and direction)
#*matrix:a 2-dimensional array of numbers
#*tensor:a n-dimensional array of numbers(when n can be any number,a 0-dimensional tensor is a sclar,a 1-dimensional tensor is a vector)

In [ ]:
tf.variable

AttributeError: module 'tensorflow' has no attribute 'variable'

In [ ]:
tf.Variable

tensorflow.python.ops.variables.Variable

In [ ]:
# create the same tensor with tf.Variable() as above
changeable_tensor=tf.Variable([10,7])
unchangeable_tensor=tf.constant([10,7])
changeable_tensor,unchangeable_tensor

(<tf.Variable 'Variable:0' shape=(2,) dtype=int32, numpy=array([10,  7], dtype=int32)>,
 <tf.Tensor: shape=(2,), dtype=int32, numpy=array([10,  7], dtype=int32)>)

In [ ]:
# how about we try .assign()
changeable_tensor[0].assign(7)
changeable_tensor

<tf.Variable 'Variable:0' shape=(2,) dtype=int32, numpy=array([7, 7], dtype=int32)>

###creating random tensors
random tensors are tensors of some arbitary size which contain random numbers

In [ ]:
# Import TensorFlow
import tensorflow as tf
print(tf.__version__)

2.17.1


In [ ]:
not_shuffled=tf.constant([[10,7],
                          [3,4],
                          [2,5]])
not_shuffled.ndim

2

In [ ]:
### shuffle the order of elements in a tensor
not_shuffled=tf.constant([[10,7],
                           [3,4],
                           [2,5]])
not_shuffled.ndim

IndentationError: unexpected indent (<ipython-input-1-32f611bf1428>, line 2)

In [ ]:
### shuffle the order of elements in a tensor
not_shuffled=tf.constant([[10,7],
                           [3,4],
                           [2,5]])
not_shuffled.ndim

NameError: name 'tf' is not defined

In [ ]:
### shuffle the order of elements in a tensor
not_shuffled=tf.constant([[10,7],
                           [3,4],
                           [2,5]])
tf.random.shuffle(not_shuffled)

NameError: name 'tf' is not defined

In [ ]:
import tensorflow as tf
### shuffle the order of elements in a tensor
not_shuffled=tf.constant([[10,7],
                           [3,4],
                           [2,5]])
tf.random.shuffle(not_shuffled)

<tf.Tensor: shape=(3, 2), dtype=int32, numpy=
array([[ 2,  5],
       [ 3,  4],
       [10,  7]], dtype=int32)>

In [ ]:
tf.random.shuffle(not_shuffled)

<tf.Tensor: shape=(3, 2), dtype=int32, numpy=
array([[ 3,  4],
       [10,  7],
       [ 2,  5]], dtype=int32)>

In [ ]:
chandu=tf.constant(7,2,4)
chandu

<tf.Tensor: shape=(4,), dtype=float64, numpy=array([7., 7., 7., 7.])>

In [ ]:
chandu=tf.constant([[1,2],
                    [2,3],
                    [4,3]])
tf.random.shuffle(chandu)

<tf.Tensor: shape=(3, 2), dtype=int32, numpy=
array([[4, 3],
       [1, 2],
       [2, 3]], dtype=int32)>

In [ ]:
tf.random.shuffle(not_shuffled,seed=42)

<tf.Tensor: shape=(3, 2), dtype=int32, numpy=
array([[ 2,  5],
       [ 3,  4],
       [10,  7]], dtype=int32)>

In [ ]:
tf.random.set_seed(42)#global level random seed
tf.random.shuffle(not_shuffled,seed=42)#operation level random

<tf.Tensor: shape=(3, 2), dtype=int32, numpy=
array([[10,  7],
       [ 3,  4],
       [ 2,  5]], dtype=int32)>

In [ ]:
#create a tensor of all ones
tf.ones([10,1])

<tf.Tensor: shape=(10, 1), dtype=float32, numpy=
array([[1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.]], dtype=float32)>

In [ ]:
#create a tensor of all zeroes
tf.zeros(shape=(3,4))

<tf.Tensor: shape=(3, 4), dtype=float32, numpy=
array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]], dtype=float32)>

In [ ]:
tf.ones([10,1])

<tf.Tensor: shape=(10, 1), dtype=float32, numpy=
array([[1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.]], dtype=float32)>

In [ ]:
tf.ones(shape(4,3))

NameError: name 'shape' is not defined

In [ ]:
tf.ones(shape=(3,4))

<tf.Tensor: shape=(3, 4), dtype=float32, numpy=
array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]], dtype=float32)>

#you can also turn numpyarrays into tensors.the amin difference between numpy arrays and tensorflow tensors is that tensors can be run on a GPU computing
bold text

In [ ]:
A=tf.constant(numpy_A)

NameError: name 'numpy_A' is not defined

In [ ]:
import numpy as np
numpy_a=np.arrange(1,25,dtype=np.int32)#create a numpy array between 1 and 25
#X=tf.constant(some_matrix)#capital for matrix or tensor
#Y=tf.constant(vector)#non-capital for vector


AttributeError: module 'numpy' has no attribute 'arrange'

In [3]:
import tensorflow as tf
rank_4_tensor=tf.zeros(shape=[2,3,4,5])
rank_4_tensor

<tf.Tensor: shape=(2, 3, 4, 5), dtype=float32, numpy=
array([[[[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]],

        [[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]],

        [[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]]],


       [[[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]],

        [[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]],

        [[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]]]], dtype=float32)>

In [ ]:
#get various attributes of our tensor
print("Datatype of every element:",rank_4_tensor.dtype)
print("Number of dimensions(rank):",rank_4_tensor.ndim)
print("Shape of tensor:",rank_4_tensor.shape)
print("elements along the 0 axis:",rank_4_tensor.shape[0])
print("")